<?php

namespace Ronald2Wing\LaravelGa4;

/**
 * Google Analytics 4 (GA4) tracking service for Laravel.
 *
 * This service handles GA4 script generation with automatic Livewire integration
 * detection for Single Page Application (SPA) navigation tracking.
 *
 * @see https://developers.google.com/analytics/devguides/collection/ga4
 */
class Ga4Service
{
    /** @var string Livewire class name for detection. */
    public const LIVEWIRE_CLASS_NAME = 'Livewire\\Livewire';

    /** @var array<string, string> Service configuration. */
    private array $config;

    /**
     * Create a new GA4 service instance.
     *
     * @param  array<string, string>  $config  Service configuration
     */
    public function __construct(array $config)
    {
        $this->config = $config;
    }

    /**
     * Check if GA4 tracking should be rendered.
     *
     * Returns true only when a valid measurement ID is configured.
     *
     * @return bool True if tracking should be rendered
     */
    private function shouldRender(): bool
    {
        return $this->getMeasurementId() !== '';
    }

    /**
     * Get the configured measurement ID.
     *
     * Returns empty string if not configured or invalid.
     * Validates that the measurement ID is a non-empty string.
     *
     * @return string Measurement ID or empty string if invalid
     */
    private function getMeasurementId(): string
    {
        $measurementId = $this->config['measurement_id'] ?? '';

        if (! is_string($measurementId)) {
            return '';
        }

        return trim($measurementId);
    }

    /**
     * Check if Livewire is installed in the application.
     *
     * @return bool True if Livewire package is available
     */
    private function isLivewireInstalled(): bool
    {
        return class_exists(self::LIVEWIRE_CLASS_NAME);
    }

    /**
     * Generate Livewire-specific JavaScript for SPA navigation tracking.
     *
     * @param  string  $measurementId  Valid GA4 measurement ID
     * @return string JavaScript code for Livewire integration
     */
    private function generateLivewireScript(string $measurementId): string
    {
        return <<<'JS'
                // Livewire SPA navigation tracking
                document.addEventListener('livewire:navigated', () => {
                    gtag('event', 'page_view', {
                        page_title: document.title,
                        page_location: window.location.href,
                        page_path: window.location.pathname + window.location.search
                    });
                });
            JS;
    }

    /**
     * Generate core GA4 initialization JavaScript.
     *
     * @param  string  $measurementId  Valid GA4 measurement ID
     * @return string Core GA4 JavaScript code
     */
    private function generateCoreScript(string $measurementId): string
    {
        $escapedMeasurementId = json_encode($measurementId, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP);

        return <<<JS
                // Google Analytics 4 initialization
                // Generated by Laravel GA4 package: https://github.com/ronald2wing/Laravel-GA4
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());
                gtag('config', {$escapedMeasurementId}, { send_page_view: false });
            JS;
    }

    /**
     * Render GA4 tracking script HTML.
     *
     * Returns complete HTML script tag with GA4 tracking code.
     * Includes automatic Livewire SPA navigation detection when Livewire is installed.
     *
     * @return string GA4 tracking script HTML or empty string if not configured
     */
    public function render(): string
    {
        if (! $this->shouldRender()) {
            return '';
        }

        $measurementId = $this->getMeasurementId();
        $javaScript = $this->generateCoreScript($measurementId);

        if ($this->isLivewireInstalled()) {
            $javaScript .= "\n".$this->generateLivewireScript($measurementId);
        }

        return $this->generateHtmlOutput($measurementId, $javaScript);
    }

    /**
     * Generate HTML output with escaped values for safe embedding.
     *
     * @param  string  $measurementId  Valid GA4 measurement ID
     * @param  string  $javaScript  JavaScript code to embed
     * @return string Complete HTML script tag with escaped values
     */
    private function generateHtmlOutput(string $measurementId, string $javaScript): string
    {
        $escapedMeasurementId = htmlspecialchars($measurementId, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');

        return <<<HTML
                <!-- Google Analytics 4 (GA4) Tracking -->
                <script async src="https://www.googletagmanager.com/gtag/js?id={$escapedMeasurementId}"></script>
                <script>
                {$javaScript}
                </script>
            HTML;
    }
}
